# -*- coding: utf-8 -*-
"""Faktor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18z_Ro5b8H1j--7NUF4xmTIXDfru_Ynfo
"""

import re
c = input()

find_ints = re.findall(r'\d+', c) 
factor_list = list(map(int, find_ints)) 


if factor_list[0]==1 or factor_list[1]==1:
  print(factor_list[0]*factor_list[1])
else:
  print(factor_list[0] * (factor_list[1]-1) +1)

factor_list.clear()